sass:
  style: :compressed
  sass_dir: theme/_sass
gems:
  - jekyll-redirect-from
language: en
baseurl: 
prose:
  metadata:
    _posts:
      - name: layout
        field:
          element: hidden
          value: post
      - name: title
        field:
          element: text
      - name: author
        field:
          element: text
